### ISSUE TITLE
How to disable dropdownMenu on flag-container?

### ISSUE THREAD

**Issue by somq** [webcat12345/ngx-intl-tel-input#210]
I'd like to let `enableAutoCountrySelect` do the magic alone and simply disable the flag selection dropdown.
Is there any way to simply disable `dropdownMenu` on `flag-container`?

I also confirm (#205) that `flag-container` is still clickable when input is `disabled`.

[EDIT]
I tricked the thing by setting elements to `display: none` until a better solution is found

```scss
/deep/ ngx-intl-tel-input .country-dropdown,
/deep/ ngx-intl-tel-input .iti-arrow {
  display: none !important;
}
```
