### ISSUE TITLE
Reduce Width

### ISSUE THREAD

**Issue by Zgon7** [webcat12345/ngx-intl-tel-input#237]
Hi. Please how can I reduce the width of the box please ?
Thank you.
![Capture](https://user-images.githubusercontent.com/46463907/71372943-f18bca00-25b5-11ea-99f6-a200566916b4.JPG)

**Comment by pasevin** [comment]
Override css:

```css
.intl-tel-input .country-list {
	box-shadow: none;
	font-size: 14px;
	margin-left: 0;
	width: 261px;
	max-height: 170px;
}
```

![image](https://user-images.githubusercontent.com/1058469/76443867-26006c80-63d4-11ea-8176-cd410cd9955f.png)

**Comment by RaminGe** [comment]
Here the responsive way to solve this issue:

``` css
.iti {
     width: 100%;
} 

.iti__flag-container {
     right: 0 !important;
}

.iti--allow-dropdown input {
     width: 100%;
}

.country-dropdown {
      width: 100% !important;
}

.iti__country-list {
     width: 100%;
}

/* To prevent name overflowing for long countries and small widths: */
.iti__country-name {
     max-width: 100%;
     overflow: hidden;
     text-overflow: ellipsis;
}
```

That way the whole element takes the width if the parent and scales accordingly.
